language: java
jdk:
  - openjdk6
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5fac6ad4b355549c9f4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
before_install: sudo apt-get update
install: sudo apt-get --fix-missing install gradle
before_script: gradle setupCIWorkspace -S
script: gradle build -S
after_script: gradle clean -S
env:
  global:
    TERM=dumb
